In [1]:
import torch
import numpy as np
import warnings
import matplotlib.pyplot as plt
warnings.filterwarnings("ignore")

## BackPropagation using PyTorch

In [2]:
x = torch.tensor(4.0, requires_grad=True)
x

tensor(4., requires_grad=True)

In [3]:
y = x**2
y

tensor(16., grad_fn=<PowBackward0>)

In [4]:
### Backpropagation y = 2*x
y.backward()

In [5]:
x.grad

tensor(8.)

#### Using List

In [6]:
data = [[1.3,2.2,3.1], [4.1,5.4,6.7], [7.2,8.3,9.5]]
torch_input = torch.tensor(data, requires_grad=True)
torch_input

tensor([[1.3000, 2.2000, 3.1000],
        [4.1000, 5.4000, 6.7000],
        [7.2000, 8.3000, 9.5000]], requires_grad=True)

In [7]:
### y = x^3 + x^2
y = torch_input**3 + torch_input**2
y

tensor([[  3.8870,  15.4880,  39.4010],
        [ 85.7310, 186.6240, 345.6530],
        [425.0880, 640.6770, 947.6250]], grad_fn=<AddBackward0>)

In [9]:
### Backpropagation
z = y.sum()
z

tensor(2690.1738, grad_fn=<SumBackward0>)

In [10]:
z.backward()

In [12]:
3*1.3**2+2*1.3

7.67

In [11]:
### y=3x^2+2x
torch_input.grad

tensor([[  7.6700,  18.9200,  35.0300],
        [ 58.6300,  98.2800, 148.0700],
        [169.9200, 223.2700, 289.7500]])