In [1]:
import torch as to
import numpy as np
import warnings
warnings.filterwarnings('ignore')
to.__version__

'1.5.1'

In [2]:
lst = list(np.arange(1000))
print(type(lst))
print(lst[:10])

<class 'list'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [3]:
lst = np.array(lst)
print(type(lst))
print(lst[:10])

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]


In [4]:
lst = to.from_numpy(np.arange(10000))
print(type(lst))
print(lst[:10])

<class 'torch.Tensor'>
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)


In [5]:
lst[3] = 100
lst[:10]

tensor([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9], dtype=torch.int32)

In [6]:
tensor_lst = to.tensor(lst)
tensor_lst[:10]

tensor([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9], dtype=torch.int32)

In [7]:
to.arange(10, 100) + to.arange(30, 120)

tensor([ 40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,  62,  64,  66,
         68,  70,  72,  74,  76,  78,  80,  82,  84,  86,  88,  90,  92,  94,
         96,  98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122,
        124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150,
        152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178,
        180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206,
        208, 210, 212, 214, 216, 218])

In [8]:
a = to.tensor([3, 4, 5], dtype = to.float)
b = to.tensor([5, 6, 7], dtype = to.float)

to.tensor(a+b)

tensor([ 8., 10., 12.])

In [9]:
inputs = to.arange(2, 4)
zeros = to.zeros_like(inputs)
print(zeros, inputs)
zeros + inputs

tensor([0, 0]) tensor([2, 3])


tensor([2, 3])

In [10]:
to.tensor(np.arange(1, 16).reshape(5, 3), dtype=to.float64)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.]], dtype=torch.float64)

In [11]:
to.add(to.arange(10, 100), to.arange(10, 100))

tensor([ 20,  22,  24,  26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,
         48,  50,  52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,
         76,  78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
        104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
        132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158,
        160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186,
        188, 190, 192, 194, 196, 198])

In [12]:
c = to.zeros(100, dtype=to.int64)
a = to.arange(0, 100, dtype=to.int64)
b = to.arange(100, 200, dtype=to.int64)

to.add(a, b, out=c)
print(c)

tensor([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126,
        128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
        156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
        184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208, 210,
        212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234, 236, 238,
        240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260, 262, 264, 266,
        268, 270, 272, 274, 276, 278, 280, 282, 284, 286, 288, 290, 292, 294,
        296, 298])


In [13]:
a = to.arange(0, 100, dtype=to.int64)
b = to.arange(100, 200, dtype=to.int64)

type(a+b)

torch.Tensor

In [14]:
a = to.arange(0, 10, dtype=to.int64)
b = to.arange(10, 20, dtype=to.int64)

print(to.add(a, b))
print(to.add(a, b).sum())

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])
tensor(190)


In [15]:
to.arange(1, 6)

tensor([1, 2, 3, 4, 5])

In [16]:
print(to.arange(1, 6).median())

tensor(3)


In [17]:
a = to.randint(1, 10, (3, 3))
b = to.randint(1, 10, (3, 3))

print(a+b)

tensor([[17,  7, 15],
        [14,  2, 13],
        [10,  5,  9]])


In [18]:
to.rand(10, 2) ## r, c

tensor([[0.0640, 0.5910],
        [0.0733, 0.0776],
        [0.7862, 0.3468],
        [0.8536, 0.3969],
        [0.5404, 0.8151],
        [0.8408, 0.6895],
        [0.8103, 0.5461],
        [0.2229, 0.6918],
        [0.0800, 0.7220],
        [0.6588, 0.7293]])

In [19]:
a, b

(tensor([[9, 6, 9],
         [7, 1, 5],
         [6, 2, 6]]),
 tensor([[8, 1, 6],
         [7, 1, 8],
         [4, 3, 3]]))

In [20]:
print(a.mul(b))

tensor([[72,  6, 54],
        [49,  1, 40],
        [24,  6, 18]])


In [21]:
a, b

(tensor([[9, 6, 9],
         [7, 1, 5],
         [6, 2, 6]]),
 tensor([[8, 1, 6],
         [7, 1, 8],
         [4, 3, 3]]))

In [22]:
print(a.T) ### Transpose a
print(b.T) ### Transpose b

tensor([[9, 7, 6],
        [6, 1, 2],
        [9, 5, 6]])
tensor([[8, 7, 4],
        [1, 1, 3],
        [6, 8, 3]])


In [23]:
a = to.arange(1, 4)
b = to.arange(2, 5)

a, b

(tensor([1, 2, 3]), tensor([2, 3, 4]))

In [24]:
a.dot(b)

tensor(20)

### Matrix Multiplication

In [25]:
a = to.tensor([[1, 2, 3], [1, 2, 3]], dtype=to.int64)
b = to.tensor([[1, 2, 3], [1, 2, 3]], dtype=to.int64)

a, b

(tensor([[1, 2, 3],
         [1, 2, 3]]),
 tensor([[1, 2, 3],
         [1, 2, 3]]))

In [26]:
a*b

tensor([[1, 4, 9],
        [1, 4, 9]])

In [27]:
to.mul(a, b)

tensor([[1, 4, 9],
        [1, 4, 9]])

In [28]:
a, b.reshape(3, 2)

(tensor([[1, 2, 3],
         [1, 2, 3]]),
 tensor([[1, 2],
         [3, 1],
         [2, 3]]))

In [29]:
to.matmul(a, b.reshape(3, 2))

tensor([[13, 13],
        [13, 13]])

In [30]:
to.mm(a, b.reshape(3, 2))

tensor([[13, 13],
        [13, 13]])